version: "3.7"

services:
  postgres:
    image: postgres:12.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=chalmers
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    depends_on:
      - postgres
    image: chalmersproject/api:master-103cc90
    ports:
      - 8080:80
    environment:
      - API_ENV=development
      - API_LOG=warn,api=debug
      - API_CORS_ORIGIN=*
      - API_DATABASE_URL=postgres://postgres@postgres/chalmers
      - API_DATABASE_MAX_CONNECTIONS=4
      - API_FIREBASE_PROJECT_ID=chalmers-api

volumes:
  postgres: {}
