[build]
publish = "dist"
command = "yarn build"


# Proxy GraphQL API requests.
[[redirects]]
from = "/api/graphql"
to = "https://api.chalmersproject.com/graphql"
status = 200


[[redirect]]
from = "/shelter/:slug/admin"
to = "/shelter/[slug]/admin.html"
status = 200

[[redirect]]
from = "/shelter/:slug"
to = "/shelter/[slug].html"
status = 200

[[redirects]]
from = "/*"
to = "/404.html"
status = 200
