[build]
publish = "dist"
command = "yarn build"

[[plugins]]
package = "netlify-plugin-cache-nextjs"


# Proxy GraphQL API requests.
[[redirects]]
from = "/api/graphql"
to = "https://api.chalmersproject.com/graphql"
status = 200


[[redirect]]
from = "/shelter/:slug/admin"
to = "/shelter/[slug]/admin.html"
status = 200

[[redirect]]
from = "/shelter/*/admin"
to = "/shelter/[slug]/admin.html"
status = 200

[[redirect]]
from = "/shelter/:slug"
to = "/shelter/[slug].html"
status = 200

[[redirect]]
from = "/shelter/*"
to = "/shelter/[slug].html"
status = 200

